export type User = {
  terms: boolean;
  email: string;
  gender: string;
  canton: string;
  country: string;
  password: string;
  province: string;
  lastName: string;
  district: string;
  services: boolean;
  firstName: string;
  birthDate: string;
  superappUser: boolean;
  documentType: string | number;
  mobilePhone1: string;
  documentNumber: string;
  codSAC: number;
  createdAt: string;
  emailId: number;
  firstMedicalRecordComplete: 0;
  fullName: string;
  isMedic: { type: string; data: [0] };
  isPatient: { type: string; data: [1] };
  secondName: string;
  status: string;
  statusCode: number;
  updatedAt: string;
  userId: number;
};

export type ISignUpBody = {
  terms: boolean;
  email: string;
  gender: string;
  canton: string;
  country: string;
  password: string;
  province: string;
  lastName: string;
  district: string;
  services: boolean;
  firstName: string;
  birthDate: string;
  superappUser: boolean;
  documentType: string | number;
  mobilePhone1: string;
  documentNumber: string;
};
